Add unit tests
5neepy/reflection_refraction pull request #2
Opened 2021-12-02 09:32 UTC by 5neepy

2021-12-02 20:35 UTC, 5neepy commented
![image](https://user-images.githubusercontent.com/67063888/144498815-380ee4ea-ead4-438f-9a2c-a3173afd0644.png)
**Istg I didn't changed anything.**

2021-12-02 20:37 UTC, 5neepy commented
I think the problem might be about that python thinks that rr_light is a module, not a directory with modules. I watched a pretty good yt tutorial about __init__.py files and now I think I understand them better.

2021-12-03 09:12 UTC, ptrtmv requested changes

2021-12-03 09:12 UTC, ptrtmv commented on tests/test_reflection_refraction.py
> +    assert beta == 90
you can remove the extra `beta==90` check. it is already checked in the line above

2021-12-03 09:12 UTC, ptrtmv commented on rr_light/reflection_refraction.py
> +        return False
Instead of the if with the two return statements you can directly write 

```
    return theta >= 45 and n1 > n2
```

which is the same

2021-12-12 18:28 UTC, 5neepy commented
Let's merge the unit tests

2021-12-14 07:22 UTC, ptrtmv commented on rr_light/reflection_refraction.py
> +    return plt.show()
Do you need the return statement here?

2021-12-14 07:33 UTC, ptrtmv commented on rr_light/reflection_refraction.py
> +    return plt.show()
We can remove this in the next MR

2021-12-14 07:34 UTC, ptrtmv approved these changes

2021-12-14 07:35 UTC, merged